### PR TITLE
Support for multiple applications

### PR DESCRIPTION
**Pull request by estum**
This pull request provides optional support for registering multiple certificates and using right ones when sending notification.

Firstly, to use this feature, we should manually require `apn/multiple_apps` after the common library will be loaded or set the environment variable `APN_MULTIPLE_APPS=true` (**note:** it's also required when we want to run specs with this feature).

Then we should set default options and register our apps by running something like the following:

```ruby
require "apn/multiple_apps"
APN.root = "/some/dir/with/certs" # it will be used as default for each apps registered after
APN::Application.register('default', certificate_name: 'default_apn_certificate.pem', password: '123')
APN::Application.register('other', certificate_name: 'other_apn_certificate.pem')
APN.default_app_name = 'other' # by default: 'default'
```

And, finally, to notify to the specified app we should just inject `app: 'name'` in a hash of notification arguments (don't worry, it will not be used in `APN::Notification.new` method):

```
APN.notify_sync(token, alert: "hi!", app: "com.example.paid")
```

The almost "real world" example:

```ruby
notification = { alert: "hi!" }
user.devices.each do |device|
  APN.notify_async(device.token, notification.merge(app: device.app))
end
```

And, pardon, but I've also updated `.gitignore` and `gemspec` files, which ones have bothered me for a long time.

### CODE REVIEW

**Comment by ryanrlhh** [comment]
@arthurnn Do you have a timeline when this feature could be merged into master?

**Comment by arthurnn** [comment]
@ryanrlhh not sure TBH.
@estum can you rebase this , and I will take a final look?
thanks

**Comment by arthurnn** [comment]
merged #85 .

**Comment by Passerby** [comment]
How to feedback multiple applications?

**Pull request closed without merging**
